### ISSUE TITLE
关于flutter中Provider

### ISSUE THREAD

**Issue by yayxs** [todother/flutter_douyin_demo#2]
大佬，provider 是写在main.dart 的顶层好一些，还是用到的页面再使用呢？
有看您的B站课程，希望能梳理一下  与后台交互的逻辑，其中使用provider，多谢

**Comment by todother** [comment]
> 大佬，provider 是写在main.dart 的顶层好一些，还是用到的页面再使用呢？
> 有看您的B站课程，希望能梳理一下 与后台交互的逻辑，其中使用provider，多谢

你好，个人建议不要在顶层把所有provider都初始化，最好在每个需要使用的地方分别进行声明。毕竟每个provider的初始化都需要一定的时间。。谁都不想打开app时间太慢。
